### ISSUE TITLE
Register LearnBase

### ISSUE THREAD

**Issue by tbreloff** [JuliaML/META#11]
I think we can register LearnBase early, while we're still working through the design of the rest of JuliaML, as then we can add it to the REQUIRE files.  The reason not to register is primarily if we think the design will change drastically from what it is now, which I don't expect.  Thoughts?

**Comment by Evizero** [comment]
I agree

**Comment by Evizero** [comment]
is it 0.5 compatible (can't think of a reason why it shouldn't)? I have not upgraded yet, but we should maybe make sure v0.5 works out of the box

**Comment by Evizero** [comment]
and then go ahead and register. I am currently working on a package where I would already like it in my REQUIRE file

**Comment by Evizero** [comment]
done

**Comment by tbreloff** [comment]
:tada: Thanks Christof
