### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Evizero** [JuliaML/META#2]
Not the most pressing of issues, but I felt like giving it the idea a shot.

It's supposed to resemble clustering, but it may have been better in my head :-). Also I would like to mention that it is derived from the original logo. I don't know if that causes issues

![tst](https://cloud.githubusercontent.com/assets/10854026/11099765/7c46d464-88ad-11e5-8ef9-4d8bf5ce4daa.png)

**Comment by ViralBShah** [comment]
Looks like a good start and better than the generic one.

**Comment by tbreloff** [comment]
Building on your idea @Evizero:

![tmp](https://cloud.githubusercontent.com/assets/933338/11102636/acc79c8a-888b-11e5-8051-c0012c0d3c83.png)

**Comment by tbreloff** [comment]
Actually this is a little cleaner:

![tmp](https://cloud.githubusercontent.com/assets/933338/11103428/511a9c98-8890-11e5-964a-995cb4c12f4a.png)

**Comment by StefanKarpinski** [comment]
Nice.

**Comment by tbreloff** [comment]
If anyone's curious how it was made (or if you want to tweak it), here it is: https://github.com/tbreloff/ExamplePlots.jl/blob/master/examples/ml_logo.ipynb

**Comment by Evizero** [comment]
The current one seems nice and appropriate. I'll close this issue for now until some Picasso comes along and convinces us otherwise
