### ISSUE TITLE
Org name

### ISSUE THREAD

**Issue by tbreloff** [JuliaML/META#3]
It seems like the name change to JuliaLearn didn't change the URL.  Which name do people prefer?  Is it worth the hassle?

**Comment by Evizero** [comment]
what's wrong with JuliaML? I think the name is pretty descriptive

**Comment by tbreloff** [comment]
To be fair, ML is obvious to you, but not necessarily to others.  It also nicely includes deep learning, which many like to distinguish from machine learning for some reason.  In the end it's a matter of preference, and I prefer to avoid acronyms if possible.

**Comment by ViralBShah** [comment]
I see - I just changed the name, but what I need to do is rename the repo. Let's leave it as is for now - and see what others have to say.

**Comment by tbreloff** [comment]
I changed it back to JuliaML... I think it's fine, unless there's agreement among the community that it should be changed.
