### ISSUE TITLE
MLPlots

### ISSUE THREAD

**Issue by tbreloff** [JuliaML/META#5]
I'm thinking about moving [MLPlots](https://github.com/tbreloff/MLPlots.jl) here.  The idea is that MLPlots is a collection of recipes for ML visualization, and recipes are loaded dynamically (with the Requires package) based on what other packages you are using.  As an example, you can visualize a neural net state in OnlineAI, or plot the history from the ValueHistories package.

Any reservations/issues with the move?  Please keep the package in mind when you're building visualizations that others might want to use.

**Comment by Evizero** [comment]
+1

**Comment by Evizero** [comment]
Maybe we should flag it as being _"in development"_ for now?

**Comment by tbreloff** [comment]
Yes it's certainly a work in progress, but it's "WIP: more visualizations needed" as opposed to "WIP: unusable".  My hope is that people can start to use it and add their own recipes (or at least those that they think other people will want to use).  This should be something that many from the community have a hand in... not just me.

**Comment by Evizero** [comment]
No objections here. The whole org is a WIP currently anyhow. baby steps

**Comment by tbreloff** [comment]
This is done: https://github.com/JuliaML/MLPlots.jl

I hope more people want to contribute cool recipes now!! :+1:
